version: '3'
services:
  gamelog:
    container_name: player
    build:
      context: .
      dockerfile: DOCKERFILE.Dockerfile

    env_file:
      - .env.docker
      
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - playerNet

networks:
  playerNet:
    external: true